/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ListingId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Text;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const DiscountCode = IDL.Record({
  'id' : IDL.Text,
  'expiresAt' : IDL.Opt(Timestamp),
  'code' : IDL.Text,
  'createdAt' : Timestamp,
  'usageCount' : IDL.Nat,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'usageLimit' : IDL.Opt(IDL.Nat),
  'updatedAt' : Timestamp,
});
export const ListingStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : ListingId,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'price' : IDL.Nat,
  'previewImageKey' : IDL.Opt(IDL.Text),
  'fileKey' : IDL.Opt(IDL.Text),
});
export const OrderId = IDL.Text;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'usedDiscountCode' : IDL.Opt(IDL.Text),
  'listingId' : ListingId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'discountPercent' : IDL.Opt(IDL.Nat),
  'updatedAt' : Timestamp,
  'amount' : IDL.Nat,
  'paymentIntentId' : IDL.Opt(IDL.Text),
});
export const SubscriptionId = IDL.Text;
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
});
export const Subscription = IDL.Record({
  'id' : SubscriptionId,
  'status' : SubscriptionStatus,
  'stripeSubscriptionId' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'currentPeriodEnd' : Timestamp,
  'updatedAt' : Timestamp,
});
export const ReviewId = IDL.Text;
export const ReviewStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'status' : ReviewStatus,
  'listingId' : ListingId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'comment' : IDL.Text,
  'updatedAt' : Timestamp,
  'rating' : IDL.Nat,
});
export const AppUserRole = IDL.Variant({
  'admin' : IDL.Null,
  'regular' : IDL.Null,
  'subscribed' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : AppUserRole,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'isBanned' : IDL.Bool,
});
export const Analytics = IDL.Record({
  'totalOrders' : IDL.Nat,
  'topListings' : IDL.Vec(IDL.Tuple(ListingId, IDL.Nat)),
  'activeSubscribers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'monthlyRevenue' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'subscriptionExpired' : IDL.Null,
  'newListing' : IDL.Null,
  'wishlistPriceDrop' : IDL.Null,
  'subscriptionRenewalWarning' : IDL.Null,
  'earlyAccessListing' : IDL.Null,
  'adminAnnouncement' : IDL.Null,
  'purchaseCompleted' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'relatedEntityId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
});
export const WishlistSnapshot = IDL.Record({
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'isPublic' : IDL.Bool,
  'listingIds' : IDL.Vec(ListingId),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWishlist' : IDL.Func([ListingId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([UserId], [], []),
  'clearReadNotifications' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDiscountCode' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(Timestamp), IDL.Opt(IDL.Nat)],
      [DiscountCode],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ListingStatus,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Listing],
      [],
    ),
  'createOrder' : IDL.Func(
      [ListingId, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Order],
      [],
    ),
  'createSubscription' : IDL.Func([IDL.Text, Timestamp], [Subscription], []),
  'deactivateDiscountCode' : IDL.Func([IDL.Text], [], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'deleteReview' : IDL.Func([ReviewId], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getApprovedReviews' : IDL.Func([ListingId], [IDL.Vec(Review)], ['query']),
  'getCallerNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWishlist' : IDL.Func([], [IDL.Opt(WishlistSnapshot)], ['query']),
  'getDiscountCodes' : IDL.Func([], [IDL.Vec(DiscountCode)], ['query']),
  'getDownloadFileUrl' : IDL.Func([ListingId], [IDL.Opt(IDL.Text)], ['query']),
  'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getPublicWishlist' : IDL.Func(
      [UserId],
      [IDL.Opt(WishlistSnapshot)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'markOrderAsRefunded' : IDL.Func([OrderId], [], []),
  'moderateReview' : IDL.Func([ReviewId, ReviewStatus], [], []),
  'removeFromWishlist' : IDL.Func([ListingId], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'sendAdminAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setWishlistVisibility' : IDL.Func([IDL.Bool], [], []),
  'submitReview' : IDL.Func([ListingId, IDL.Nat, IDL.Text], [Review], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unbanUser' : IDL.Func([UserId], [], []),
  'updateListing' : IDL.Func(
      [
        ListingId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ListingStatus,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Listing],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateSubscriptionStatus' : IDL.Func(
      [SubscriptionId, SubscriptionStatus],
      [],
      [],
    ),
  'validateDiscountCode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : DiscountCode, 'error' : IDL.Text })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ListingId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Text;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const DiscountCode = IDL.Record({
    'id' : IDL.Text,
    'expiresAt' : IDL.Opt(Timestamp),
    'code' : IDL.Text,
    'createdAt' : Timestamp,
    'usageCount' : IDL.Nat,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'usageLimit' : IDL.Opt(IDL.Nat),
    'updatedAt' : Timestamp,
  });
  const ListingStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : ListingId,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'price' : IDL.Nat,
    'previewImageKey' : IDL.Opt(IDL.Text),
    'fileKey' : IDL.Opt(IDL.Text),
  });
  const OrderId = IDL.Text;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'usedDiscountCode' : IDL.Opt(IDL.Text),
    'listingId' : ListingId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'discountPercent' : IDL.Opt(IDL.Nat),
    'updatedAt' : Timestamp,
    'amount' : IDL.Nat,
    'paymentIntentId' : IDL.Opt(IDL.Text),
  });
  const SubscriptionId = IDL.Text;
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'id' : SubscriptionId,
    'status' : SubscriptionStatus,
    'stripeSubscriptionId' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'currentPeriodEnd' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const ReviewId = IDL.Text;
  const ReviewStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'status' : ReviewStatus,
    'listingId' : ListingId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'comment' : IDL.Text,
    'updatedAt' : Timestamp,
    'rating' : IDL.Nat,
  });
  const AppUserRole = IDL.Variant({
    'admin' : IDL.Null,
    'regular' : IDL.Null,
    'subscribed' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : AppUserRole,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'isBanned' : IDL.Bool,
  });
  const Analytics = IDL.Record({
    'totalOrders' : IDL.Nat,
    'topListings' : IDL.Vec(IDL.Tuple(ListingId, IDL.Nat)),
    'activeSubscribers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'monthlyRevenue' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'subscriptionExpired' : IDL.Null,
    'newListing' : IDL.Null,
    'wishlistPriceDrop' : IDL.Null,
    'subscriptionRenewalWarning' : IDL.Null,
    'earlyAccessListing' : IDL.Null,
    'adminAnnouncement' : IDL.Null,
    'purchaseCompleted' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'relatedEntityId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
  });
  const WishlistSnapshot = IDL.Record({
    'userId' : UserId,
    'updatedAt' : Timestamp,
    'isPublic' : IDL.Bool,
    'listingIds' : IDL.Vec(ListingId),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWishlist' : IDL.Func([ListingId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([UserId], [], []),
    'clearReadNotifications' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDiscountCode' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(Timestamp), IDL.Opt(IDL.Nat)],
        [DiscountCode],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ListingStatus,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Listing],
        [],
      ),
    'createOrder' : IDL.Func(
        [ListingId, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Order],
        [],
      ),
    'createSubscription' : IDL.Func([IDL.Text, Timestamp], [Subscription], []),
    'deactivateDiscountCode' : IDL.Func([IDL.Text], [], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'deleteReview' : IDL.Func([ReviewId], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getApprovedReviews' : IDL.Func([ListingId], [IDL.Vec(Review)], ['query']),
    'getCallerNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWishlist' : IDL.Func([], [IDL.Opt(WishlistSnapshot)], ['query']),
    'getDiscountCodes' : IDL.Func([], [IDL.Vec(DiscountCode)], ['query']),
    'getDownloadFileUrl' : IDL.Func(
        [ListingId],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getPublicWishlist' : IDL.Func(
        [UserId],
        [IDL.Opt(WishlistSnapshot)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'markOrderAsRefunded' : IDL.Func([OrderId], [], []),
    'moderateReview' : IDL.Func([ReviewId, ReviewStatus], [], []),
    'removeFromWishlist' : IDL.Func([ListingId], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'sendAdminAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setWishlistVisibility' : IDL.Func([IDL.Bool], [], []),
    'submitReview' : IDL.Func([ListingId, IDL.Nat, IDL.Text], [Review], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unbanUser' : IDL.Func([UserId], [], []),
    'updateListing' : IDL.Func(
        [
          ListingId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ListingStatus,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Listing],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateSubscriptionStatus' : IDL.Func(
        [SubscriptionId, SubscriptionStatus],
        [],
        [],
      ),
    'validateDiscountCode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : DiscountCode, 'error' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };