/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalOrders' : bigint,
  'topListings' : Array<[ListingId, bigint]>,
  'activeSubscribers' : bigint,
  'totalRevenue' : bigint,
  'monthlyRevenue' : bigint,
}
export type AppUserRole = { 'admin' : null } |
  { 'regular' : null } |
  { 'subscribed' : null };
export interface DiscountCode {
  'id' : string,
  'expiresAt' : [] | [Timestamp],
  'code' : string,
  'createdAt' : Timestamp,
  'usageCount' : bigint,
  'discountPercent' : bigint,
  'isActive' : boolean,
  'usageLimit' : [] | [bigint],
  'updatedAt' : Timestamp,
}
export interface Listing {
  'id' : ListingId,
  'status' : ListingStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'price' : bigint,
  'previewImageKey' : [] | [string],
  'fileKey' : [] | [string],
}
export type ListingId = string;
export type ListingStatus = { 'upcoming' : null } |
  { 'published' : null } |
  { 'draft' : null };
export interface Notification {
  'id' : string,
  'title' : string,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'relatedEntityId' : [] | [string],
  'message' : string,
}
export type NotificationType = { 'subscriptionExpired' : null } |
  { 'newListing' : null } |
  { 'wishlistPriceDrop' : null } |
  { 'subscriptionRenewalWarning' : null } |
  { 'earlyAccessListing' : null } |
  { 'adminAnnouncement' : null } |
  { 'purchaseCompleted' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'usedDiscountCode' : [] | [string],
  'listingId' : ListingId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'discountPercent' : [] | [bigint],
  'updatedAt' : Timestamp,
  'amount' : bigint,
  'paymentIntentId' : [] | [string],
}
export type OrderId = string;
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null };
export interface Review {
  'id' : ReviewId,
  'status' : ReviewStatus,
  'listingId' : ListingId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'comment' : string,
  'updatedAt' : Timestamp,
  'rating' : bigint,
}
export type ReviewId = string;
export type ReviewStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'id' : SubscriptionId,
  'status' : SubscriptionStatus,
  'stripeSubscriptionId' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'currentPeriodEnd' : Timestamp,
  'updatedAt' : Timestamp,
}
export type SubscriptionId = string;
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = string;
export interface UserProfile {
  'id' : UserId,
  'username' : string,
  'createdAt' : Timestamp,
  'role' : AppUserRole,
  'email' : string,
  'updatedAt' : Timestamp,
  'isBanned' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WishlistSnapshot {
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'isPublic' : boolean,
  'listingIds' : Array<ListingId>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToWishlist' : ActorMethod<[ListingId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[UserId], undefined>,
  'clearReadNotifications' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDiscountCode' : ActorMethod<
    [string, bigint, [] | [Timestamp], [] | [bigint]],
    DiscountCode
  >,
  'createListing' : ActorMethod<
    [string, string, bigint, ListingStatus, [] | [string], [] | [string]],
    Listing
  >,
  'createOrder' : ActorMethod<
    [ListingId, bigint, [] | [string], [] | [string]],
    Order
  >,
  'createSubscription' : ActorMethod<[string, Timestamp], Subscription>,
  'deactivateDiscountCode' : ActorMethod<[string], undefined>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'deleteReview' : ActorMethod<[ReviewId], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getApprovedReviews' : ActorMethod<[ListingId], Array<Review>>,
  'getCallerNotifications' : ActorMethod<[], Array<Notification>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWishlist' : ActorMethod<[], [] | [WishlistSnapshot]>,
  'getDiscountCodes' : ActorMethod<[], Array<DiscountCode>>,
  'getDownloadFileUrl' : ActorMethod<[ListingId], [] | [string]>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'getPublicWishlist' : ActorMethod<[UserId], [] | [WishlistSnapshot]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'markOrderAsRefunded' : ActorMethod<[OrderId], undefined>,
  'moderateReview' : ActorMethod<[ReviewId, ReviewStatus], undefined>,
  'removeFromWishlist' : ActorMethod<[ListingId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], UserProfile>,
  'sendAdminAnnouncement' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWishlistVisibility' : ActorMethod<[boolean], undefined>,
  'submitReview' : ActorMethod<[ListingId, bigint, string], Review>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unbanUser' : ActorMethod<[UserId], undefined>,
  'updateListing' : ActorMethod<
    [
      ListingId,
      string,
      string,
      bigint,
      ListingStatus,
      [] | [string],
      [] | [string],
    ],
    Listing
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateSubscriptionStatus' : ActorMethod<
    [SubscriptionId, SubscriptionStatus],
    undefined
  >,
  'validateDiscountCode' : ActorMethod<
    [string],
    { 'ok' : DiscountCode } |
      { 'error' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];