/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TipStats {
    totalTips: bigint;
    tipsByProject: Array<[OpenSourceProjectId, bigint]>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DiscountCode {
    id: string;
    expiresAt?: Timestamp;
    code: string;
    createdAt: Timestamp;
    usageCount: bigint;
    discountPercent: bigint;
    isActive: boolean;
    usageLimit?: bigint;
    updatedAt: Timestamp;
}
export interface Tip {
    id: TipId;
    status: TipStatus;
    userId?: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    projectId: OpenSourceProjectId;
    amount: bigint;
    paymentIntentId?: string;
}
export interface Subscription {
    id: SubscriptionId;
    status: SubscriptionStatus;
    stripeSubscriptionId: string;
    userId: UserId;
    createdAt: Timestamp;
    currentPeriodEnd: Timestamp;
    updatedAt: Timestamp;
}
export type SubscriptionId = string;
export type ListingId = string;
export interface Analytics {
    totalOrders: bigint;
    topListings: Array<[ListingId, bigint]>;
    activeSubscribers: bigint;
    totalRevenue: bigint;
    monthlyRevenue: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type TipId = string;
export type OpenSourceProjectId = string;
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type ReviewId = string;
export interface Review {
    id: ReviewId;
    status: ReviewStatus;
    listingId: ListingId;
    userId: UserId;
    createdAt: Timestamp;
    comment: string;
    updatedAt: Timestamp;
    rating: bigint;
}
export interface OpenSourceProject {
    id: OpenSourceProjectId;
    title: string;
    suggestedTipCents: bigint;
    createdAt: Timestamp;
    description: string;
    creatorName: string;
    isActive: boolean;
    updatedAt: Timestamp;
    repoUrl: string;
    previewImageKey?: string;
}
export interface Listing {
    id: ListingId;
    status: ListingStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    price: bigint;
    previewImageKey?: string;
    fileKey?: string;
}
export interface WishlistSnapshot {
    userId: UserId;
    updatedAt: Timestamp;
    isPublic: boolean;
    listingIds: Array<ListingId>;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    usedDiscountCode?: string;
    listingId: ListingId;
    userId: UserId;
    createdAt: Timestamp;
    discountPercent?: bigint;
    updatedAt: Timestamp;
    amount: bigint;
    paymentIntentId?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = string;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Notification {
    id: string;
    title: string;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    relatedEntityId?: string;
    message: string;
}
export type OrderId = string;
export interface UserProfile {
    id: UserId;
    username: string;
    createdAt: Timestamp;
    role: AppUserRole;
    email: string;
    updatedAt: Timestamp;
    isBanned: boolean;
}
export enum AppUserRole {
    admin = "admin",
    regular = "regular",
    subscribed = "subscribed"
}
export enum ListingStatus {
    upcoming = "upcoming",
    published = "published",
    draft = "draft"
}
export enum NotificationType {
    subscriptionExpired = "subscriptionExpired",
    newListing = "newListing",
    wishlistPriceDrop = "wishlistPriceDrop",
    subscriptionRenewalWarning = "subscriptionRenewalWarning",
    earlyAccessListing = "earlyAccessListing",
    adminAnnouncement = "adminAnnouncement",
    purchaseCompleted = "purchaseCompleted"
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    refunded = "refunded"
}
export enum ReviewStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    expired = "expired"
}
export enum TipStatus {
    pending = "pending",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addToWishlist(listingId: ListingId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(userId: UserId): Promise<void>;
    clearReadNotifications(): Promise<void>;
    completeTip(tipId: TipId): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createDiscountCode(code: string, discountPercent: bigint, expiresAt: Timestamp | null, usageLimit: bigint | null): Promise<DiscountCode>;
    createListing(title: string, description: string, price: bigint, status: ListingStatus, previewImageKey: string | null, fileKey: string | null): Promise<Listing>;
    createOpenSourceProject(title: string, description: string, repoUrl: string, creatorName: string, suggestedTipCents: bigint, previewImageKey: string | null): Promise<OpenSourceProject>;
    createOrder(listingId: ListingId, amount: bigint, paymentIntentId: string | null, discountCode: string | null): Promise<Order>;
    createSubscription(stripeSubscriptionId: string, currentPeriodEnd: Timestamp): Promise<Subscription>;
    deactivateDiscountCode(codeId: string): Promise<void>;
    deleteListing(listingId: ListingId): Promise<void>;
    deleteOpenSourceProject(id: OpenSourceProjectId): Promise<void>;
    deleteReview(reviewId: ReviewId): Promise<void>;
    getAllOpenSourceProjects(): Promise<Array<OpenSourceProject>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllReviews(): Promise<Array<Review>>;
    getAllSubscriptions(): Promise<Array<Subscription>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAnalytics(): Promise<Analytics>;
    getApprovedReviews(listingId: ListingId): Promise<Array<Review>>;
    getCallerNotifications(): Promise<Array<Notification>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWishlist(): Promise<WishlistSnapshot | null>;
    getDiscountCodes(): Promise<Array<DiscountCode>>;
    getDownloadFileUrl(listingId: ListingId): Promise<string | null>;
    getListings(): Promise<Array<Listing>>;
    getOpenSourceProjects(): Promise<Array<OpenSourceProject>>;
    getProjectTips(projectId: OpenSourceProjectId): Promise<Array<Tip>>;
    getPublicWishlist(userId: UserId): Promise<WishlistSnapshot | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTipStats(): Promise<TipStats>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserOrders(): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSubscriptions(): Promise<Array<Subscription>>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(notificationId: string): Promise<void>;
    markOrderAsRefunded(orderId: OrderId): Promise<void>;
    moderateReview(reviewId: ReviewId, status: ReviewStatus): Promise<void>;
    recordTip(projectId: OpenSourceProjectId, amount: bigint, paymentIntentId: string | null): Promise<Tip>;
    removeFromWishlist(listingId: ListingId): Promise<void>;
    saveCallerUserProfile(username: string, email: string): Promise<UserProfile>;
    sendAdminAnnouncement(title: string, message: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setWishlistVisibility(isPublic: boolean): Promise<void>;
    submitReview(listingId: ListingId, rating: bigint, comment: string): Promise<Review>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unbanUser(userId: UserId): Promise<void>;
    updateListing(listingId: ListingId, title: string, description: string, price: bigint, status: ListingStatus, previewImageKey: string | null, fileKey: string | null): Promise<Listing>;
    updateOpenSourceProject(id: OpenSourceProjectId, title: string, description: string, repoUrl: string, creatorName: string, suggestedTipCents: bigint, previewImageKey: string | null, isActive: boolean): Promise<OpenSourceProject>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<void>;
    updateSubscriptionStatus(subscriptionId: SubscriptionId, status: SubscriptionStatus): Promise<void>;
    validateDiscountCode(code: string): Promise<{
        __kind__: "ok";
        ok: DiscountCode;
    } | {
        __kind__: "error";
        error: string;
    }>;
}
import type { AppUserRole as _AppUserRole, DiscountCode as _DiscountCode, Listing as _Listing, ListingId as _ListingId, ListingStatus as _ListingStatus, Notification as _Notification, NotificationType as _NotificationType, OpenSourceProject as _OpenSourceProject, OpenSourceProjectId as _OpenSourceProjectId, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, Review as _Review, ReviewId as _ReviewId, ReviewStatus as _ReviewStatus, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, SubscriptionId as _SubscriptionId, SubscriptionStatus as _SubscriptionStatus, Timestamp as _Timestamp, Tip as _Tip, TipId as _TipId, TipStatus as _TipStatus, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, WishlistSnapshot as _WishlistSnapshot, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addToWishlist(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async clearReadNotifications(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearReadNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearReadNotifications();
            return result;
        }
    }
    async completeTip(arg0: TipId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTip(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createDiscountCode(arg0: string, arg1: bigint, arg2: Timestamp | null, arg3: bigint | null): Promise<DiscountCode> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiscountCode(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
                return from_candid_DiscountCode_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiscountCode(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
            return from_candid_DiscountCode_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createListing(arg0: string, arg1: string, arg2: bigint, arg3: ListingStatus, arg4: string | null, arg5: string | null): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, to_candid_ListingStatus_n15(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Listing_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, to_candid_ListingStatus_n15(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Listing_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOpenSourceProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string | null): Promise<OpenSourceProject> {
        if (this.processError) {
            try {
                const result = await this.actor.createOpenSourceProject(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5));
                return from_candid_OpenSourceProject_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOpenSourceProject(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5));
            return from_candid_OpenSourceProject_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: ListingId, arg1: bigint, arg2: string | null, arg3: string | null): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Order_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Order_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSubscription(arg0: string, arg1: Timestamp): Promise<Subscription> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscription(arg0, arg1);
                return from_candid_Subscription_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscription(arg0, arg1);
            return from_candid_Subscription_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateDiscountCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateDiscountCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateDiscountCode(arg0);
            return result;
        }
    }
    async deleteListing(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deleteOpenSourceProject(arg0: OpenSourceProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOpenSourceProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOpenSourceProject(arg0);
            return result;
        }
    }
    async deleteReview(arg0: ReviewId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async getAllOpenSourceProjects(): Promise<Array<OpenSourceProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOpenSourceProjects();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOpenSourceProjects();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptions();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptions();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getApprovedReviews(arg0: ListingId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedReviews(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedReviews(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerNotifications();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerNotifications();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWishlist(): Promise<WishlistSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWishlist();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWishlist();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiscountCodes(): Promise<Array<DiscountCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscountCodes();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscountCodes();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDownloadFileUrl(arg0: ListingId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDownloadFileUrl(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDownloadFileUrl(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenSourceProjects(): Promise<Array<OpenSourceProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenSourceProjects();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenSourceProjects();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectTips(arg0: OpenSourceProjectId): Promise<Array<Tip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectTips(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectTips(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicWishlist(arg0: UserId): Promise<WishlistSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicWishlist(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicWishlist(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTipStats(): Promise<TipStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getTipStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTipStats();
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubscriptions();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubscriptions();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async markOrderAsRefunded(arg0: OrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrderAsRefunded(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrderAsRefunded(arg0);
            return result;
        }
    }
    async moderateReview(arg0: ReviewId, arg1: ReviewStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moderateReview(arg0, to_candid_ReviewStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moderateReview(arg0, to_candid_ReviewStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async recordTip(arg0: OpenSourceProjectId, arg1: bigint, arg2: string | null): Promise<Tip> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTip(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Tip_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTip(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Tip_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWishlist(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return from_candid_UserProfile_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return from_candid_UserProfile_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendAdminAnnouncement(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAdminAnnouncement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAdminAnnouncement(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setWishlistVisibility(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWishlistVisibility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWishlistVisibility(arg0);
            return result;
        }
    }
    async submitReview(arg0: ListingId, arg1: bigint, arg2: string): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return from_candid_Review_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return from_candid_Review_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unbanUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async updateListing(arg0: ListingId, arg1: string, arg2: string, arg3: bigint, arg4: ListingStatus, arg5: string | null, arg6: string | null): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, to_candid_ListingStatus_n15(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Listing_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, to_candid_ListingStatus_n15(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Listing_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOpenSourceProject(arg0: OpenSourceProjectId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string | null, arg7: boolean): Promise<OpenSourceProject> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOpenSourceProject(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_OpenSourceProject_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOpenSourceProject(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_OpenSourceProject_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSubscriptionStatus(arg0: SubscriptionId, arg1: SubscriptionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_SubscriptionStatus_n70(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_SubscriptionStatus_n70(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async validateDiscountCode(arg0: string): Promise<{
        __kind__: "ok";
        ok: DiscountCode;
    } | {
        __kind__: "error";
        error: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateDiscountCode(arg0);
                return from_candid_variant_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateDiscountCode(arg0);
            return from_candid_variant_n72(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppUserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserRole): AppUserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountCode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountCode): DiscountCode {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_OpenSourceProject_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OpenSourceProject): OpenSourceProject {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TipStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TipStatus): TipStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Tip_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tip): Tip {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WishlistSnapshot]): WishlistSnapshot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    expiresAt: [] | [_Timestamp];
    code: string;
    createdAt: _Timestamp;
    usageCount: bigint;
    discountPercent: bigint;
    isActive: boolean;
    usageLimit: [] | [bigint];
    updatedAt: _Timestamp;
}): {
    id: string;
    expiresAt?: Timestamp;
    code: string;
    createdAt: Timestamp;
    usageCount: bigint;
    discountPercent: bigint;
    isActive: boolean;
    usageLimit?: bigint;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        expiresAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.expiresAt)),
        code: value.code,
        createdAt: value.createdAt,
        usageCount: value.usageCount,
        discountPercent: value.discountPercent,
        isActive: value.isActive,
        usageLimit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.usageLimit)),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ListingId;
    status: _ListingStatus;
    title: string;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    price: bigint;
    previewImageKey: [] | [string];
    fileKey: [] | [string];
}): {
    id: ListingId;
    status: ListingStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    price: bigint;
    previewImageKey?: string;
    fileKey?: string;
} {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n20(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        price: value.price,
        previewImageKey: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.previewImageKey)),
        fileKey: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.fileKey))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OpenSourceProjectId;
    title: string;
    suggestedTipCents: bigint;
    createdAt: _Timestamp;
    description: string;
    creatorName: string;
    isActive: boolean;
    updatedAt: _Timestamp;
    repoUrl: string;
    previewImageKey: [] | [string];
}): {
    id: OpenSourceProjectId;
    title: string;
    suggestedTipCents: bigint;
    createdAt: Timestamp;
    description: string;
    creatorName: string;
    isActive: boolean;
    updatedAt: Timestamp;
    repoUrl: string;
    previewImageKey?: string;
} {
    return {
        id: value.id,
        title: value.title,
        suggestedTipCents: value.suggestedTipCents,
        createdAt: value.createdAt,
        description: value.description,
        creatorName: value.creatorName,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        repoUrl: value.repoUrl,
        previewImageKey: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.previewImageKey))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    usedDiscountCode: [] | [string];
    listingId: _ListingId;
    userId: _UserId;
    createdAt: _Timestamp;
    discountPercent: [] | [bigint];
    updatedAt: _Timestamp;
    amount: bigint;
    paymentIntentId: [] | [string];
}): {
    id: OrderId;
    status: OrderStatus;
    usedDiscountCode?: string;
    listingId: ListingId;
    userId: UserId;
    createdAt: Timestamp;
    discountPercent?: bigint;
    updatedAt: Timestamp;
    amount: bigint;
    paymentIntentId?: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n27(_uploadFile, _downloadFile, value.status),
        usedDiscountCode: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.usedDiscountCode)),
        listingId: value.listingId,
        userId: value.userId,
        createdAt: value.createdAt,
        discountPercent: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.discountPercent)),
        updatedAt: value.updatedAt,
        amount: value.amount,
        paymentIntentId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.paymentIntentId))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubscriptionId;
    status: _SubscriptionStatus;
    stripeSubscriptionId: string;
    userId: _UserId;
    createdAt: _Timestamp;
    currentPeriodEnd: _Timestamp;
    updatedAt: _Timestamp;
}): {
    id: SubscriptionId;
    status: SubscriptionStatus;
    stripeSubscriptionId: string;
    userId: UserId;
    createdAt: Timestamp;
    currentPeriodEnd: Timestamp;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_SubscriptionStatus_n31(_uploadFile, _downloadFile, value.status),
        stripeSubscriptionId: value.stripeSubscriptionId,
        userId: value.userId,
        createdAt: value.createdAt,
        currentPeriodEnd: value.currentPeriodEnd,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReviewId;
    status: _ReviewStatus;
    listingId: _ListingId;
    userId: _UserId;
    createdAt: _Timestamp;
    comment: string;
    updatedAt: _Timestamp;
    rating: bigint;
}): {
    id: ReviewId;
    status: ReviewStatus;
    listingId: ListingId;
    userId: UserId;
    createdAt: Timestamp;
    comment: string;
    updatedAt: Timestamp;
    rating: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ReviewStatus_n38(_uploadFile, _downloadFile, value.status),
        listingId: value.listingId,
        userId: value.userId,
        createdAt: value.createdAt,
        comment: value.comment,
        updatedAt: value.updatedAt,
        rating: value.rating
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    username: string;
    createdAt: _Timestamp;
    role: _AppUserRole;
    email: string;
    updatedAt: _Timestamp;
    isBanned: boolean;
}): {
    id: UserId;
    username: string;
    createdAt: Timestamp;
    role: AppUserRole;
    email: string;
    updatedAt: Timestamp;
    isBanned: boolean;
} {
    return {
        id: value.id,
        username: value.username,
        createdAt: value.createdAt,
        role: from_candid_AppUserRole_n44(_uploadFile, _downloadFile, value.role),
        email: value.email,
        updatedAt: value.updatedAt,
        isBanned: value.isBanned
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    userId: _UserId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    isRead: boolean;
    relatedEntityId: [] | [string];
    message: string;
}): {
    id: string;
    title: string;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    relatedEntityId?: string;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n49(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        isRead: value.isRead,
        relatedEntityId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.relatedEntityId)),
        message: value.message
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TipId;
    status: _TipStatus;
    userId: [] | [_UserId];
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    projectId: _OpenSourceProjectId;
    amount: bigint;
    paymentIntentId: [] | [string];
}): {
    id: TipId;
    status: TipStatus;
    userId?: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    projectId: OpenSourceProjectId;
    amount: bigint;
    paymentIntentId?: string;
} {
    return {
        id: value.id,
        status: from_candid_TipStatus_n60(_uploadFile, _downloadFile, value.status),
        userId: record_opt_to_undefined(from_candid_opt_n62(_uploadFile, _downloadFile, value.userId)),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        projectId: value.projectId,
        amount: value.amount,
        paymentIntentId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.paymentIntentId))
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    published: null;
} | {
    draft: null;
}): ListingStatus {
    return "upcoming" in value ? ListingStatus.upcoming : "published" in value ? ListingStatus.published : "draft" in value ? ListingStatus.draft : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "refunded" in value ? OrderStatus.refunded : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "expired" in value ? SubscriptionStatus.expired : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ReviewStatus {
    return "pending" in value ? ReviewStatus.pending : "approved" in value ? ReviewStatus.approved : "rejected" in value ? ReviewStatus.rejected : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    regular: null;
} | {
    subscribed: null;
}): AppUserRole {
    return "admin" in value ? AppUserRole.admin : "regular" in value ? AppUserRole.regular : "subscribed" in value ? AppUserRole.subscribed : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscriptionExpired: null;
} | {
    newListing: null;
} | {
    wishlistPriceDrop: null;
} | {
    subscriptionRenewalWarning: null;
} | {
    earlyAccessListing: null;
} | {
    adminAnnouncement: null;
} | {
    purchaseCompleted: null;
}): NotificationType {
    return "subscriptionExpired" in value ? NotificationType.subscriptionExpired : "newListing" in value ? NotificationType.newListing : "wishlistPriceDrop" in value ? NotificationType.wishlistPriceDrop : "subscriptionRenewalWarning" in value ? NotificationType.subscriptionRenewalWarning : "earlyAccessListing" in value ? NotificationType.earlyAccessListing : "adminAnnouncement" in value ? NotificationType.adminAnnouncement : "purchaseCompleted" in value ? NotificationType.purchaseCompleted : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): TipStatus {
    return "pending" in value ? TipStatus.pending : "completed" in value ? TipStatus.completed : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n65(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DiscountCode;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: DiscountCode;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DiscountCode_n12(_uploadFile, _downloadFile, value.ok)
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OpenSourceProject>): Array<OpenSourceProject> {
    return value.map((x)=>from_candid_OpenSourceProject_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiscountCode>): Array<DiscountCode> {
    return value.map((x)=>from_candid_DiscountCode_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tip>): Array<Tip> {
    return value.map((x)=>from_candid_Tip_n58(_uploadFile, _downloadFile, x));
}
function to_candid_ListingStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): _ReviewStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    upcoming: null;
} | {
    published: null;
} | {
    draft: null;
} {
    return value == ListingStatus.upcoming ? {
        upcoming: null
    } : value == ListingStatus.published ? {
        published: null
    } : value == ListingStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ReviewStatus.pending ? {
        pending: null
    } : value == ReviewStatus.approved ? {
        approved: null
    } : value == ReviewStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.refunded ? {
        refunded: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.cancelled ? {
        cancelled: null
    } : value == SubscriptionStatus.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
